### ISSUE TITLE
cant receive any response from udp server

### ISSUE THREAD

**Issue by Arziel** [ayumax/ObjectDeliverer#17]
Hellou, basically I can sent packets with success to my node.js udp server, but i cant successfully receive packet back from the server.

And i mean ANY packet, i tried all of the variants and event is basically never fired :/ Checked by WireShark that packets are really send to valid ports.

Is there any example for server + project which works?

**Comment by Arziel** [comment]
Ahh, found it :D its in docs

**Comment by ayumax** [comment]
It was good to find it.
Use two instances of ObjectDeliverer to send and receive via UDP.
Use "CreateProtocolUdpSocketReceiver" for the receiving protocol.
