### ISSUE TITLE
Garbage in the message

### ISSUE THREAD

**Issue by Alexorleon** [ayumax/ObjectDeliverer#19]
Hello!
I ran a sample project ObjectDelivererTest and for testing the connection I used Hercules. I tried to send a message, but a PrintString did not display anything. While in the UE itself, messages arrive.
On the UE server Deliveler Packet Rule used "Rule Size Body" with SizeLength 4 and SizeBufferEndian Big. DeliveryBox is Utf8StringDeliveryBox.
I suspect that Hercules does not add the size of the message in the header. Then I wrote a simple client on Qt and it partially worked.
The problem is that in most cases there is garbage at the end of the message. I can not understand why.
![ObjectDelivelerError](https://user-images.githubusercontent.com/8413316/57286908-8356cd80-70e0-11e9-99d5-29663d0ab9c9.png)

**Comment by ayumax** [comment]
Thank you for using ObjectDeliverer.
I examined the question.
It was found that if the end of the sent string buffer does not contain NULL, it may be garbage.
I will fix it as soon as possible.

**Comment by ayumax** [comment]
The Marketplace plugin has been updated, so please download and try it.

**Comment by Alexorleon** [comment]
Yes, everything is fine, it works! Thank!
