### ISSUE TITLE
UdpSocketReceiver crash if port is already in use

### ISSUE THREAD

**Issue by Lildreas** [ayumax/ObjectDeliverer#22]
Hallo,

thanks again (I already communicated with you a while ago) for your nice plugin!

I have a small issue: Today I made a test with the following setup:

The Windows tool "Packet Sender" was running on my computer and listening  as a server to localhost port 50569 for UDP communication.

Now I started my UE project using ObjectDeliverer as a server where I use CreateProtocolUdpSocketReceiver with the same port 50569 and then start the ObjectDelivererManager (all done in Blueprint).

I knew that it would fail because the port is already used. But I wanted to see how ObjectDeliverer would fail. :-)

Result: UE crashed, with the following crash info:
  
Assertion failed: Socket != nullptr [File:c:\program files\epic games\ue_4.22\engine\source\runtime\networking\public\Common/UdpSocketReceiver.h] [Line: 53]

UE4Editor_ObjectDeliverer_0001!UProtocolUdpSocketReceiver::Start() [c:\users\andreas.lepel\documents\unrealprojectssvn\testudp\plugins\objectdeliverer\source\objectdeliverer\private\protocol\protocoludpsocketreceiver.cpp:27]
UE4Editor_ObjectDeliverer_0001!UObjectDelivererManager::Start() [c:\users\andreas.lepel\documents\unrealprojectssvn\testudp\plugins\objectdeliverer\source\objectdeliverer\private\objectdeliverermanager.cpp:87]
UE4Editor_ObjectDeliverer_0001!UObjectDelivererManager::execStart() [c:\users\andreas.lepel\documents\unrealprojectssvn\testudp\plugins\objectdeliverer\source\objectdeliverer\public\objectdeliverermanager.h:23]
UE4Editor_CoreUObject

Maybe check the pointer and give an error, or abort gracefully?

As I wrote, this was only a test and will not happen frequently, but I thought I should tell you.

Best from Munich
Andreas

**Comment by ayumax** [comment]
I think that there is a problem with crashing, so I will fix it.
Thank you for trying.

**Comment by ayumax** [comment]
Hello Andreas,

We have fixed the reported bug and updated it to the Marketplace.
I was very helpful because I was not aware of this problem.
Thank you very much.

**Comment by Lildreas** [comment]
Hi,

thanks for the fix and the info, I just updated ObjectDeliverer.

I am very happy with your tool, I use it to send data back and forth from my Unreal app to a workstation that runs a MATLAB/Simulink simulation, using UDP (via ObjectDeliverer) and the MAVLink protocol (used e.g. to control drones) I implemented.

Best
Andreas
