### ISSUE TITLE
How to perform valid UDP bidirectional connection

### ISSUE THREAD

**Issue by Arziel** [ayumax/ObjectDeliverer#31]
Hello, for some time i still facing the same issue, but for now i moved from local (which i fixed in past, and even my local wifi network), but for now i facing a mobile hotspot.

My issue is still the same, i can't create a valid bidirectional client-server udp communication.

The client is behind the NAT and makes traversing the ports, i know what the issue is.

There should be 
* message from client to server
* client should listening on that port which used
* server should response messages to same port from which client send message 

But the problem is i don't know on what port i should listen and also, if i try listen to same port which i bound for sender, it failed because is already in use. 

Do i something wrong? It just seems for me I something missleading, cause this must be most trivial thing, which is for sure implemented somehow.

Can you please help me with some response, cause i just can't get it worked.

**Comment by Arziel** [comment]
I think I need access to socket and get on which port is client bounded to sender. From C++ code, it seems like information stored at 

`SenderSocket->GetPortNo()`, does this variable contains port number on which is socket bounded (that generated 50000+), not the one given as server port?

![image](https://user-images.githubusercontent.com/11194301/71769081-b924ae00-2f1c-11ea-9d34-fecfd5827d91.png) 

It is posible to get that number 51878 from BP plugin?

**Comment by ayumax** [comment]
Details are unknown because I am not used to communication beyond NAT.
However, if NAT supports bidirectional translation, I don't think you need to know the private IP address and port.

**Comment by Arziel** [comment]
Client itself needed that information because he must start listen at that port. :)

**Comment by Arziel** [comment]
After some hours, i make it work with combination of getnamo's udp wrapper, which i use for perform udp hole punch. :]
