### ISSUE TITLE
Result of TCP/IP Client connect

### ISSUE THREAD

**Issue by markusstephanides** [ayumax/ObjectDeliverer#36]
Hello!

ObjectDeliverer working really well, thank your for that!

But how do I get the result of the ObjectDelivererManager::Start Method to know whether the client successfully connected to the server or not and if not then also the reason of the connection failure.

Thanks in advance

**Comment by ayumax** [comment]
Use the "Connected" event to detect that you are connected.

![image](https://user-images.githubusercontent.com/8191970/80973122-ec8b3100-8e59-11ea-851a-47df0ad5dcff.png)

If the TCP / IP Client protocol of ObjectDeliverer fails to connect, it retries until it succeeds.
Therefore, we do not provide a detection method when connection fails.

**Comment by markusstephanides** [comment]
But that way the user won't be notified if he entered a wrong server or port. Could you add a event that gets called when the connection failed (with autoretry set to false)?

**Comment by ayumax** [comment]
Considering only TCP / IP clients, its functionality is easy to implement, but this library is designed to use protocols other than TCP / IP in the same way, so it's a bit difficult to achieve.
