### ISSUE TITLE
Can't read messages from external TCP client

### ISSUE THREAD

**Issue by brunoleos** [ayumax/ObjectDeliverer#44]
Hi! First, thanks for your effort!

I'm testing the sample TCP server application, and I can send messages from client 1 and 2, which are received by the server and received data is printed.

But if I try to send a packet from applications like Swiddler or Packet Sender, the receive callback from the server seems to do nothing. The breakpoint set on the server's receive event is not hit.

Sniffing with Wireshark, I can see that the packet is sent and the server replies with ACK, but the data is not displayed on Unreal log, like with the clients 1 and 2 from the sample. (I've added some print blocks to log the messages received
![github question](https://user-images.githubusercontent.com/16419952/102508999-cb7ff500-4064-11eb-8aa9-c8b972fe375b.png)
, the original example didn't have that)

What can be happening?

**Comment by ayumax** [comment]
Since the "Packet Rule" currently used is "Size Body", a 4-byte area indicating the size is required at the beginning of the buffer.
I think that it can be received by changing "Packet Rule" to "No division".

**Comment by brunoleos** [comment]
Yes, that was the issue! Thanks for the super fast answer :)
