### ISSUE TITLE
Want to use this plug-in on ue5

### ISSUE THREAD

**Issue by salier** [ayumax/ObjectDeliverer#50]
Want plug-in support for ue5 version.I prefer the new effect (but the external data cannot enter the engine normally. I hope there is an update.Support ue5

**Comment by ayumax** [comment]
I already support UE5 and have sent the updated data to Epic.
If you wait a little longer, you should be able to download it from the Marketplace.

**Comment by ayumax** [comment]
UE5 is now supported, try it out.
